# Generated by Django 5.2.14 on 2026-05-23 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor_username", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("member.create", "Member Create"),
                            ("member.update", "Member Update"),
                            ("member.activate", "Member Activate"),
                            ("member.deactivate", "Member Deactivate"),
                            ("group.add_member", "Group Add"),
                            ("group.remove_member", "Group Remove"),
                            ("import.create", "Import Create"),
                            ("import.run", "Import Run"),
                        ],
                        max_length=64,
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=255)),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"], name="audit_audit_action_0c6a84_idx"
                    ),
                    models.Index(
                        fields=["target", "-created_at"], name="audit_audit_target_d43143_idx"
                    ),
                ],
            },
        ),
    ]
