# Generated by Django 5.2.14 on 2026-05-23 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "audit event",
                "verbose_name_plural": "audit events",
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("member.create", "Member created"),
                    ("member.update", "Member updated"),
                    ("member.activate", "Member activated"),
                    ("member.deactivate", "Member deactivated"),
                    ("group.add_member", "Added to group"),
                    ("group.remove_member", "Removed from group"),
                    ("import.create", "Import created"),
                    ("import.run", "Import run"),
                ],
                max_length=64,
                verbose_name="action",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="actor",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_username",
            field=models.CharField(blank=True, max_length=255, verbose_name="actor username"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="after",
            field=models.JSONField(blank=True, null=True, verbose_name="after"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="before",
            field=models.JSONField(blank=True, null=True, verbose_name="before"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="note",
            field=models.CharField(blank=True, max_length=255, verbose_name="note"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="target",
            field=models.CharField(blank=True, max_length=255, verbose_name="target"),
        ),
    ]
