# Generated by Django 5.2.14 on 2026-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_alter_auditlog_options_alter_auditlog_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("member.create", "Member created"),
                    ("member.update", "Member updated"),
                    ("member.activate", "Member activated"),
                    ("member.deactivate", "Member deactivated"),
                    ("group.add_member", "Added to group"),
                    ("group.remove_member", "Removed from group"),
                    ("import.create", "Import created"),
                    ("import.run", "Import run"),
                    ("settings.update", "Settings updated"),
                ],
                max_length=64,
                verbose_name="action",
            ),
        ),
    ]
