# Generated by Django 5.2.14 on 2026-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "admin_group_name",
                    models.CharField(
                        default="steward-admins",
                        help_text="Name of the Authentik group whose members are admitted into Steward. Must match a real group in Authentik.",
                        max_length=255,
                        verbose_name="admin group name",
                    ),
                ),
                (
                    "invite_flow_slug",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Slug of an Authentik enrollment flow attached to invitations for new members. Leave blank to skip invitation creation.",
                        max_length=255,
                        verbose_name="invite flow slug",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "application settings",
                "verbose_name_plural": "application settings",
            },
        ),
    ]
