# Generated by Django 5.2.14 on 2026-05-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsetting",
            name="group_filter_regex",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Regex matched (via re.search) against Authentik group names. Only matching groups appear in Steward's UI. Empty shows all groups. Example: ^(union|committee)-",
                max_length=500,
                verbose_name="group filter regex",
            ),
        ),
    ]
