# Generated by Django 5.2.14 on 2026-05-23 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importjob",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "import job",
                "verbose_name_plural": "import jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="importjobrow",
            options={
                "ordering": ("row_number",),
                "verbose_name": "import job row",
                "verbose_name_plural": "import job rows",
            },
        ),
        migrations.AlterField(
            model_name="importjob",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="csv",
            field=models.FileField(upload_to="imports/", verbose_name="CSV"),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="original_filename",
            field=models.CharField(max_length=255, verbose_name="original filename"),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preview", "Preview ready"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="summary",
            field=models.JSONField(blank=True, default=dict, verbose_name="summary"),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by",
            ),
        ),
        migrations.AlterField(
            model_name="importjobrow",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("skip", "Skip"),
                    ("error", "Error"),
                ],
                max_length=16,
                verbose_name="action",
            ),
        ),
        migrations.AlterField(
            model_name="importjobrow",
            name="applied",
            field=models.BooleanField(default=False, verbose_name="applied"),
        ),
        migrations.AlterField(
            model_name="importjobrow",
            name="authentik_pk",
            field=models.IntegerField(blank=True, null=True, verbose_name="Authentik pk"),
        ),
        migrations.AlterField(
            model_name="importjobrow",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="importjobrow",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                to="imports.importjob",
                verbose_name="job",
            ),
        ),
        migrations.AlterField(
            model_name="importjobrow",
            name="message",
            field=models.CharField(blank=True, max_length=500, verbose_name="message"),
        ),
        migrations.AlterField(
            model_name="importjobrow",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="importjobrow",
            name="row_number",
            field=models.PositiveIntegerField(verbose_name="row number"),
        ),
        migrations.AlterField(
            model_name="importjobrow",
            name="x_number",
            field=models.CharField(blank=True, max_length=64, verbose_name="X-Number"),
        ),
    ]
